Laba3/Laba3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('concerts/', include('concerts.urls')),
    path('admin/', admin.site.urls),
]

Laba3/concerts/urls.py
from django.urls import path

from . import views

app_name = 'concerts'
urlpatterns = [
	path('', views.index, name='index'),
	path('load', views.load, name='load'),
	path('create', views.create, name='create'),
	path('<int:concert_id>/remove', views.remove, name='remove'),
	path('<int:concert_id>/detail', views.detail, name='detail'),
	path('<int:concert_id>/edit', views.edit, name='edit'),
	path('logs', views.logs, name='logs'),
]

Laba3/concerts/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = 	False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.db.utils import IntegrityError
import json

class Concerts(models.Model):
	concert_id = models.AutoField(primary_key=True)
	band = models.ForeignKey('Bands', models.DO_NOTHING)
	place = models.ForeignKey('Places', models.DO_NOTHING)
	org = models.ForeignKey('Organizers', models.DO_NOTHING)
	date = models.DateField()
	price = models.FloatField()
	description = models.TextField(blank=True, null=True)

	class Meta:
		managed = False
		db_table = 'concerts'


	def load_from_json(self):
		with open('concerts/concerts.json', 'r') as f:
			obj = json.load(f)
			Concerts.objects.all().delete()
			Bands.objects.all().delete()
			Places.objects.all().delete()
			Organizers.objects.all().delete()
			for c in obj:
				self.add_row(c)

	def add_row(self, row):
		b = Bands(b_name= row['band']['b_name'], country = row['band']['country'], albums_num = row['band']['albums_num'])
		b.save()
	
		pl = Places(pl_name= row['place']['pl_name'], city = row['place']['city'], capacity = row['place']['capacity'])
		pl.save()
			
		org = Organizers(org_name= row['organizer']['org_name'], commercial = row['organizer']['commercial'])
		org.save()
	
		if not Concerts.objects.all().filter(band_id=b.band_id, place_id=pl.place_id, org_id=org.org_id):
 			self = Concerts(band_id=b.band_id, place_id=pl.place_id, org_id=org.org_id, date=row['date'], price=row['price'], description=row['description'])
 			self.save()		


	def __str__(self):
		tupl = (self.concert_id, Bands.objects.get(pk = self.band_id), Places.objects.get(pk = self.place_id), 
			Organizers.objects.get(pk = self.org_id), self.price, self.date, self.description)
		return "{'id':%s, 'band':%s, 'place':%s, 'org':%s, 'price':%s, 'date':%s, 'description':%s} " % tupl


class Bands(models.Model):
	band_id = models.AutoField(primary_key=True)
	b_name = models.CharField(max_length=45)
	country = models.CharField(max_length=45)
	albums_num = models.IntegerField()

	class Meta:
		managed = False
		db_table = 'bands'

	def __str__(self):
		return "{'band_id': %s, 'b_name': %s, 'country': %s, 'albums_num': %s}" % (self.band_id, self.b_name, self.country, self.albums_num)


class Organizers(models.Model):
	org_id = models.AutoField(primary_key=True)
	org_name = models.CharField(max_length=45)
	commercial = models.BooleanField()

	class Meta:
		managed = False
		db_table = 'organizers'

	def __str__(self):
		return "{'org_id': %s, 'org_name': %s, 'commercial': %s}" % (self.org_id, self.org_name, self.commercial)


class Places(models.Model):
	place_id = models.AutoField(primary_key=True)
	pl_name = models.CharField(max_length=45)
	city = models.CharField(max_length=45)
	capacity = models.IntegerField()

	class Meta:
		managed = False
		db_table = 'places'

	def __str__(self):
		return "{'place_id': %s, 'pl_name': %s, 'city': %s, 'capacity': %s}" % (self.place_id, self.pl_name, self.city, self.capacity)
 

Laba3/concerts/forms.py
from django import forms
from .models import Concerts, Bands, Places, Organizers

class BandForm(forms.ModelForm):
	class Meta:
		model = Bands
		fields = ( 'b_name', 'country', 'albums_num')
		labels = { 'b_name': 'Name',
				'albums_num':'Albums numbers'}  

class ConcertForm(forms.ModelForm):
	class Meta:
		model = Concerts
		fields = ('price', 'date', 'description')


class OrganizerForm(forms.ModelForm):
	class Meta:
		model = Organizers
		fields = ( 'org_name', 'commercial',)
		labels = { 'org_name': 'Name',
				'commercial':'Is commercial'}


class PlaceForm(forms.ModelForm):
	class Meta:
		model = Places
		fields = ( 'pl_name', 'city', 'capacity',)
		labels = { 'pl_name': 'Name',
				'capacity':'Place capacity'}

Laba3/concerts/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.db import connection
from collections import namedtuple
from concerts.models import Concerts, Bands, Places, Organizers 
from .forms import BandForm, ConcertForm, OrganizerForm, PlaceForm

# Create your views here.

def load(request):
	c = Concerts()
	c.load_from_json()
	return HttpResponseRedirect(reverse('concerts:index'))


def index(request):
	concerts = Concerts.objects.all();
	curs = connection.cursor();
	if request.method == "POST":
		data = request.POST  
		if not (data['comm'] == ""):
			concerts = concerts.filter(org__in=Organizers.objects.all().filter(commercial=data['comm']))
		if not ((data['bdate'] == "") and (data['tdate'] == "")):
			concerts = concerts.filter(date__range=(data['bdate'], data['tdate']))
		if not (data['word'] == ""):
			concerts = concerts.filter(description__iregex=data['word'])
		return render(request, 'concerts/base.html', {'concerts': concerts})
	else:
		return render(request, 'concerts/base.html', {'concerts': concerts}) 
	

def remove(request, concert_id):
	if request.method == "POST":
		Concerts.objects.get(pk = concert_id).delete()		 
	return HttpResponseRedirect(reverse('concerts:index'))


def detail(request, concert_id):
	if request.method == "POST":
		return HttpResponseRedirect(reverse('concerts:index'))
	else:
		concert = Concerts.objects.get(pk=concert_id)
		return render(request, 'concerts/detail.html', {'concert': concert})


def edit(request, concert_id):
	concert = get_object_or_404(Concerts, pk = concert_id)
	band = Bands.objects.get(pk = concert.band_id)
	place = Places.objects.get(pk = concert.place_id)
	org = Organizers.objects.get(pk = concert.place_id)
	if request.method == "POST":
		b_form = BandForm(request.POST, instance=band)
		pl_form = PlaceForm(request.POST, instance=place)
		org_form = OrganizerForm(request.POST, instance=org)
		con_form = ConcertForm(request.POST, instance=concert)
		
		concert.date=con_form['date'].value() 
		concert.price=con_form['price'].value()
		concert.description=con_form['description'].value()
		concert.save()
		band.b_name=b_form['b_name'].value()
		band.country=b_form['country'].value()
		band.albums_num=b_form['albums_num'].value()
		band.save()
		place.pl_name=pl_form['pl_name'].value()
		place.city=pl_form['city'].value()
		place.capacity=pl_form['capacity'].value()
		place.save()
		org.org_name=org_form['org_name'].value()
		org.commercial=org_form['commercial'].value()
		org.save()

		return HttpResponseRedirect(reverse('concerts:index'))
	else:
		con_form = ConcertForm(instance=concert)
		b_form = BandForm(instance=band)
		pl_form = PlaceForm(instance=place)
		org_form = OrganizerForm(instance=org)
	return render(request, 'concerts/edit.html', {'concert_id':concert_id, 'con_form':con_form, 'b_form':b_form,
													'pl_form':pl_form, 'org_form':org_form})


def create(request):
	if request.method == "POST":
		b_form = BandForm(request.POST)
		pl_form = PlaceForm(request.POST)
		org_form = OrganizerForm(request.POST)
		con_form = ConcertForm(request.POST)
		
		row = {'date': con_form['date'].value(),
				'price': con_form['price'].value(),
				'band': {'b_name': b_form['b_name'].value(), 
						'country': b_form['country'].value(),
						'albums_num': b_form['albums_num'].value()},
				'place': {'pl_name': pl_form['pl_name'].value(),
						'city': pl_form['city'].value(),
						'capacity': pl_form['capacity'].value()},
				'organizer': {'org_name': org_form['org_name'].value(),
							'commercial': org_form['commercial'].value()},
				'description': con_form['description'].value(),
				}
		c = Concerts()
		c.add_row(row)
		return HttpResponseRedirect(reverse('concerts:index'))
	else:
		con_form = ConcertForm()
		b_form = BandForm()
		pl_form = PlaceForm()
		org_form = OrganizerForm()
	return render(request, 'concerts/create.html', {'con_form':con_form, 'b_form':b_form, 'pl_form':pl_form, 'org_form':org_form})


def logs(request):
	curs = connection.cursor()
	curs.execute("select * from logs")
	logs = fetchall(curs)
	return render(request, 'concerts/logs.html', {'logs':logs})



def fetchall(curs):
		desc = curs.description
		nt_result = namedtuple('Result', [col[0] for col in desc])
		return [nt_result(*row) for row in curs.fetchall()]

Laba3/concerts/templates/concerts/base.html
{% load staticfiles %}
<html>
	<head>
		<title> Concetrs schedule </title>
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/concerts.css' %}">
	</head>

	<body>
		<div class="page-header">
			<h1>Concerts Schedule</h1>
		</div>

		<div>
			<h5 class="search col-md-1">Search</h5> 
			<div class="forms-search">
				<form action="{% url 'concerts:index'%}" method="post">
					{% csrf_token %}
					<div class="col-md-2">
						<label for="comm" >commercial: </label>
						<input id="comm" type="text" name="comm" placeholder="True/False" class="text-field" pattern="(True)|(False)" size="8">
					</div>
					<div class="col-md-3">
						<label for="bdate">date: from </label>
						<input id="bdate" type="text" name="bdate" class="text-field" placeholder="yyyy-mm-dd" size="9" pattern="[0-9]{4}-(0[0-9]|1[0-2])-([0-2][0-9]|3[0-1])">
						<label for="tdate"> to </label>
						<input id="tdate" type="text" name="tdate" class="text-field" placeholder="yyyy-mm-dd" size="9" pattern="[0-9]{4}-(0[0-9]|1[0-2])-([0-2][0-9]|3[0-1])">
					</div>
					<div class="col-md-4"> 
						<label for="word">search in description: </label>
						<input id="word" type="text" size="15" name="word" class="text-field">
					
						<button class="btn" type="confirm">
							<span class="glyphicon glyphicon-search"></span>
						</button>
					</div>
					<button form="trigger" class="btn col-md-1 col-md-offset-0">
  						Trigger on/off
					</button>
				</form>
				<form id="trigger" action="{% url 'concerts:index' %}">
				</form>
			</div>
		</div>

		<hr align="center">
		<table class="table table-striped table-hover table-condensed">
			<thead>
				<tr>
					<th>Band</th>
					<th>Place</th>
					<th>City</th>
					<th>Organizer</th>
					<th>Price</th>
					<th>Date</th>
					<th>Description</th>
					<th class="edit-btn"></th>
					<th class="edit-btn"></th>	
					<th class="edit_btn"></th>
				</tr>
			</thead>
			<tbody>
			{% for c in concerts %}	
				<tr>
					<th>{{c.band.b_name}}</th>
					<th>{{c.place.pl_name}}</th>
					<th>{{c.place.city}}</th>
					<th>{{c.org.org_name}}</th>
					<th>{{c.price}}</th>
					<th>{{c.date}}</th>
					<th>{{c.description}}</th>
					<th class="edit-btn">
						<form action="{% url 'concerts:detail' c.concert_id %}">
							<button type="submit" class="btn  btn-sm">
								<span class="glyphicon glyphicon-option-horizontal"></span>
							</button>
						</form>
					</th>
					<th class="edit-btn">
						<form action="{% url 'concerts:edit' c.concert_id %}">
							<button type="submit" class="btn btn-success btn-sm">
								<span class="glyphicon glyphicon-pencil"></span>
							</button>
						</form>
					</th>
					<th class="edit-btn">
						<form action="{% url 'concerts:remove' c.concert_id %}" method="post">
							{% csrf_token %}
							<button type="submit" class="btn btn-danger btn-sm">
								<span class="glyphicon glyphicon-minus"></span>
							</button>
						</form>
					</th>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	
		<div class="col-lg-2 col-lg-offset-4 col-sm-2 col-sm-offset-3 col-xs-2 col-xs-offset-3">	
			<form action="{% url 'concerts:create'%}">
				<button type="submit" class="btn btn-success btn-block btn-sm"> 
					<span class="glyphicon glyphicon-plus"></span>
				</button>
			</form>
		</div> <div class="col-lg-2 col-lg-offset-1 col-sm-2 col-sm-offset-5 col-xs-3 col-xs-offset-4">
			<form action="{% url 'concerts:logs' %}">
				<button type="submit" class="btn btn-block btn-sm">Logs</button>
			</form>
		</div> <div class="col-lg-2 col-sm-2 col-xs-3">
			<form action="{% url 'concerts:load' %}">
				<button type="submit" class="btn btn-block btn-sm">Reload data</button>
			</form>
		</div>
	</body>
</html>

Laba3/concerts/templates/concerts/create.html
{% load staticfiles %}
<html>
	<head>
		<title> Concetrs schedule </title>
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/concerts.css' %}">
	</head>

	<body>
		<div class="page-header">
			<h1>Concerts Schedule</h1>
		</div>

		<form id="form" method="POST" action="{% url 'concerts:create'%}">
			{% csrf_token %}
			<div class="row">
				<h4 class="col-md-3 col-md-offset-1">Band information</h4>
				<h4 class="col-md-3">Place and Date</h4>
				<h4 class="col-md-3">Organizer</h4>
			</div>
			<div class="row">
				<div class="col-md-2 col-md-offset-1">{{b_form.as_p}}</div>
				<div class="col-md-2">{{ pl_form.as_p}}</div>
        		<div class="col-md-2">{{ con_form.as_p}}</div>
       			<div class="col-md-2">{{ org_form.as_p}}</div> 
			</div>
        </form>
        
        <div class="row">
        	<form id="cancel" action="{% url 'concerts:index' %}">
			</form>
			<button form="cancel" class="btn col-md-1 col-md-offset-1 btn-md" type="submit">Cancel</button>
			<button form="form" class="btn btn-success col-md-1 col-md-offset-1 btn-md" type="submit">Save</button>
		</div>
	</body>
</html>

Laba3/concerts/templates/concerts/detail.html
{% load staticfiles %}
<html>
	<head>
		<title> Concetrs schedule </title>
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/concerts.css' %}">
	</head>

	<body scroll="true">
		<div class="page-header">
			<h1>Concerts Schedule</h1>
		</div>

		<form id="edit" action="{% url 'concerts:edit' concert.concert_id%}">
		<div class="row">
			<h4 class="col-md-3 col-md-offset-1">Band information</h4>
			<h4 class="col-md-3">Place and Date</h4>
			<h4 class="col-md-3">Organizer</h4>
		</div>
		<div class="row">
			<div class="col-md-2 col-md-offset-1">
				<p>
					<label for="id_b_name">Name:</label> 
					<input disabled="true" name="b_name" value="{{concert.band.b_name}}" required="" maxlength="45" id="id_b_name" type="text">
				</p>
				<p>
					<label for="id_country">Country:</label> 
					<input disabled="true" name="country" value="{{concert.band.country}}" required="" maxlength="45" id="id_country" type="text">
				</p>
				<p>
					<label for="id_albums_num">Albums numbers:</label> 
					<input disabled="true" name="albums_num" value="{{concert.band.albums_num}}" required="" id="id_albums_num" type="number">
				</p>
			</div>
			<div class="col-md-2">
				<p>
					<label for="id_pl_name">Name:</label> 
					<input disabled="true" name="pl_name" value="{{concert.place.pl_name}}" required="" maxlength="45" id="id_pl_name" type="text">
				</p>
				<p>
					<label for="id_city">City:</label> 
					<input disabled="true" name="city" value="{{concert.place.city}}" required="" maxlength="45" id="id_city" type="text">
				</p>
				<p>
					<label for="id_capacity">Place capacity:</label> 
					<input disabled="true" name="capacity" value="{{concert.place.capacity}}" required="" id="id_capacity" type="number">
				</p>
			</div>
        	<div class="col-md-2">
        		<p>
        			<label for="id_price">Price:</label> 
        			<input disabled="true" name="price" value="{{concert.price}}" required="" id="id_price" step="any" type="number">
        		</p>
				<p>
					<label for="id_date">Date:</label> 
					<input disabled="true" name="date" value="{{concert.date}}" required="" id="id_date" type="text">
				</p>
				<p>
					<label for="id_description">Description:</label> 
					<textarea disabled="true" name="description" rows="10" id="id_description" cols="40">{{concert.description}}</textarea>
				</p>
			</div>
       		<div class="col-md-2">
       			<p>
       				<label for="id_org_name">Name:</label> 
       				<input disabled="true" name="org_name" value="{{concert.org.org_name}}" required="" maxlength="45" id="id_org_name" type="text">
       			</p>	
				<p>
					<label for="id_commercial">Is commercial:</label> 
					<input disabled="true" name="commercial" value="{{concert.org.commercial}}" id="id_commercial" type="checkbox">
				</p>
			</div> 
		</div>
		 </form>

		<div class="row">
       		<form id="cancel" action="{% url 'concerts:index'%}"></form>
       		<button form="cancel" type="submit" class="btn btn-default col-md-1 col-md-offset-1 btn-md">Cancel</button>
       		<button form="edit" type="submit" class="btn btn-success col-md-1 col-md-offset-1 btn-md">Edit</button>
    	</div>

    </body>
</html>

Laba3/concerts/templates/concerts/edit.html
{% load staticfiles %}
<html>
	<head>
		<title> Concetrs schedule </title>
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/concerts.css' %}">
	</head>

	<body>
		<div class="page-header">
			<h1>Concerts Schedule</h1>
		</div>

		<form id="form" method="POST" action="{% url 'concerts:edit' concert_id %}" class="post-form">
			{% csrf_token %}
			<div class="row">
				<h4 class="col-md-3 col-md-offset-1">Band information</h4>
				<h4 class="col-md-3">Place and Date</h4>
				<h4 class="col-md-3">Organizer</h4>
			</div>
			<div class="row">
				<div class="col-md-2 col-md-offset-1">{{b_form.as_p}}</div>
				<div class="col-md-2">{{ pl_form.as_p}}</div>
        		<div class="col-md-2">{{ con_form.as_p}}</div>
       			<div class="col-md-2">{{ org_form.as_p}}</div> 
			</div>
        </form>

        <div class="row">
        	<form id="cancel" action="{% url 'concerts:index' %}">
			</form>
			<button form="cancel" class="btn col-md-1 col-md-offset-1 btn-md" type="submit">Cancel</button>
			<button form="form" class="btn btn-success col-md-1 col-md-offset-1 btn-md" type="submit">Save</button>
		</div>
	</body>
</html>

Laba3/concerts/templates/concerts/logs.html
{% load staticfiles %}
<html>
	<head>
		<title> Concetrs schedule </title>
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/concerts.css' %}">
	</head>

	<body>
		<div class="page-header">
			<h1>Concerts Schedule</h1>
		</div>

		<table class="table table-striped table-hover table-condensed">
			<thead>
				<tr>
					<th>ID</th>
					<th>Row ID</th>
					<th>Message</th>
					<th>Time</th>
			</thead>
			<tbody>
			{% for l in logs %}	
				<tr>
					<th>{{l.id}}</th>
					<th>{{l.row_id}}</th>
					<th>{{l.msg}}</th>
					<th>{{l.time}}</th>
				</tr>
			{% endfor %}
			</tbody>
		</table>

		<div class="row">
       		<form id="cancel" action="{% url 'concerts:index'%}"></form>
       		<button form="cancel" type="submit" class="btn col-md-1 col-md-offset-1 btn-md">Cancel</button>
       		<button form="reload" type="submit" class="btn col-md-1 col-md-offset-1 btn-md">Reload</button>
    	</div>
    	<form id="reload" action="{% url 'concerts:logs' %}""></form>
	</body>
</html>